apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  myapp
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name:  myapp
        image: nginx:stable-alpine3.17
        ports:
        - containerPort: 80
